### ISSUE TITLE
Step 1 embedding_generation.py requires pickle file

### ISSUE THREAD

**Issue by wiersmalab** [minhaoJ2/TaxoEnrich#4]
For "Step 1: Generate the embeddings for the existing taxonomy" there is no mention of a creating a pickle file, however, the code requires it:
```

    with open('./data/MAG_CS/computer_science.pickle.bin', 'rb') as f:
        data = pickle.load(f)
        g_full = data['g_full']
        name = data['name']
        vocab = data["vocab"]
        train_node_ids = data["train_node_ids"]
        validation_node_ids = data["validation_node_ids"]
        test_node_ids = data["test_node_ids"]
```

I thought that according to the instructions the pickle file is generated  in "Step 2" using `generate_dataset_binary.py`.

**Comment by minhaoJ2** [comment]
It assumes that the train/dev/test split is given already in the existing pickle file. However, if not, you can run generate_binary_dataset.py first with existing_partition as 0. In this case, the output pickle file would contain the split dataset as required.
