### ISSUE TITLE
SemEval_Noun\SemEval_Verb dataset question

### ISSUE THREAD

**Issue by GitHubBoys** [minhaoJ2/TaxoEnrich#5]
Thanks for your nick work! 
SemEval_Noun\SemEval_Verb dataset format is different from MAG-CS\MAG-PSY, how to process the data。

**Comment by minhaoJ2** [comment]
Since the SemEval datasets are much larger than MAG datasets, I didn't upload the processed embeddings and related files. Please refer to embedding_generation.py for details on generating the embeddings.

**Comment by GitHubBoys** [comment]
thank you for your reply!!!
MAG:
<img width="277" alt="image" src="https://github.com/minhaoJ2/TaxoEnrich/assets/15064119/eef1195f-96cc-4e36-8131-ea4d48410950">
<img width="213" alt="image" src="https://github.com/minhaoJ2/TaxoEnrich/assets/15064119/092e556c-5949-4286-9115-346cdcbd9775">

WORDNET:
<img width="335" alt="image" src="https://github.com/minhaoJ2/TaxoEnrich/assets/15064119/a3245cdc-c915-476b-af16-6914139d4247">
<img width="480" alt="image" src="https://github.com/minhaoJ2/TaxoEnrich/assets/15064119/6b5dcf12-383e-47ab-be41-b1a4e8ea5f22">

The MAG dataset is clear that taxo nodes are just a conceptual term,
But the wordnet_noun dataset,For example, entity.n.01 entity||entity.n.01 in the wordnet_noun.term file,
Is this embedding entity||entity.n.01 as a whole? Will it affect the encoding

**Comment by GitHubBoys** [comment]
And when I run the generate_dataset_binary.py file, I encountered the same problem as the  [#issue3](https://github.com/minhaoJ2/TaxoEnrich/issues/3)
<img width="1199" alt="image" src="https://github.com/minhaoJ2/TaxoEnrich/assets/15064119/5ae389dc-921b-48d7-b267-4aa89df1feb1">
can you tell me your gensim version

**Comment by minhaoJ2** [comment]
Hi, thank you for your questions. For the term format, you are correct that BERT cannot directly encode .n.01 in the terms. So if I remember correctly, the pure word was extracted from this format in the preprocessing. And I used the newsest version of gensim in the experiments.

**Comment by GitHubBoys** [comment]
Thanks for the reply, got it. The last question can you upload a full version of the MAG_CS data that can be run? The one provided in github is a test version, the embedding is incomplete. I can't run the embedding file now.
<img width="190" alt="image" src="https://github.com/minhaoJ2/TaxoEnrich/assets/15064119/8e6042cd-b1c2-42f5-9bb6-2966f1d85147">
<img width="1283" alt="image" src="https://github.com/minhaoJ2/TaxoEnrich/assets/15064119/ed15795d-9784-4aaf-9b00-16d766533a8b">

**Comment by minhaoJ2** [comment]
If the file link is not working for you, please run the generate embedding file to generate the corresponding embeddings. I do not have processed data now since the experiments were finished two years ago. Sorry for the inconvenience.

**Comment by wangyudong1997** [comment]
你好这个程序的环境是怎么样的，总是报错

**Comment by GitHubBoys** [comment]
> 

给的数据集不全，运行不了

**Comment by GitHubBoys** [comment]
> 你好这个程序的环境是怎么样的，总是报错

给的数据集不全，运行不了
